# Generated by Django 6.1 on 2026-08-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('taille_effectif', models.PositiveIntegerField(blank=True, null=True, verbose_name="Taille (nombre d'employés)")),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('date_enquete', models.DateField(verbose_name="Date d'enquête")),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations libres')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
            ],
            options={
                'verbose_name': 'Entreprise collectée',
                'verbose_name_plural': 'Entreprises collectées',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name="Secteur d'activité")),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name="Type d'activité")),
            ],
            options={
                'verbose_name': "Type d'activité",
                'verbose_name_plural': "Types d'activité",
                'ordering': ['nom'],
            },
        ),
    ]
