# Generated by Django 6.1 on 2026-08-13 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collecte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='enqueteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes', to=settings.AUTH_USER_MODEL, verbose_name='Enquêteur'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collecte.secteuractivite', verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='type_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collecte.typeactivite', verbose_name="Type d'activité"),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['enqueteur'], name='collecte_en_enquete_e9abd8_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['date_enquete'], name='collecte_en_date_en_829180_idx'),
        ),
    ]
